version: "2.4"
services:
  process_manager_server:
    build:
      context: ./server
      dockerfile: DockerfileServer
    runtime: nvidia
    ports:
      - "3305:3306"
      - "5983:5983"
    volumes:
      - "/media:/media:ro"
      - "./data/programs:/home/docker/process-manager/data/programs"
      - "./server/src:/home/docker/process-manager/server/src"
      - "mysql_data:/var/lib/mysql"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    container_name: server
    tty: true

  process_manager_app:
    build:
      context: ./client
      dockerfile: DockerfileApp
    ports:
      - "8080:8080"
    container_name: app
    tty: true

volumes:
  mysql_data:
