name: pytorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2020.6.20
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - dbus=1.13.6
  - expat=2.2.9
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.2
  - gmp=6.2.0
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - harfbuzz=2.7.2
  - hdf5=1.10.6
  - icu=67.1
  - intel-openmp=2020.2
  - jasper=1.900.1
  - jpeg=9d
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=10.0.1
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.66.2
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm10=10.0.1
  - libnghttp2=1.41.0
  - libopencv=4.5.0
  - libpng=1.6.37
  - libpq=12.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.40.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mysql-common=8.0.21
  - mysql-libs=8.0.21
  - ncurses=6.2
  - nettle=3.4.1
  - ninja=1.10.1
  - nspr=4.29
  - nss=3.58
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - opencv=4.5.0
  - openh264=2.1.1
  - openssl=1.1.1h
  - pcre=8.44
  - pillow=8.0.1
  - pip=20.2.4
  - pixman=0.38.0
  - pthread-stubs=0.4
  - py-opencv=4.5.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - python=3.8.3
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.7.0
  - qt=5.12.9
  - readline=8.0
  - setuptools=50.3.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - torchvision=0.8.1
  - tornado=6.0.4
  - tqdm=4.50.2
  - typing_extensions=3.7.4.3
  - wheel=0.35.1
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - torchsummary==1.5.1

