name: keras
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.1.0
  - absl-py=0.11.0
  - aiohttp=3.6.3
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - attrs=20.2.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - cachetools=4.1.1
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=3.1.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - cycler=0.10.0
  - dbus=1.13.18
  - expat=2.2.10
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gast=0.3.3
  - gettext=0.19.8.1
  - glib=2.63.1
  - gmp=6.2.0
  - gnutls=3.6.13
  - google-auth=1.22.1
  - google-auth-oauthlib=0.4.2
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - graphviz=2.42.3
  - grpcio=1.31.0
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.10.0
  - harfbuzz=2.7.2
  - hdf5=1.10.6
  - icu=67.1
  - idna=2.10
  - importlib-metadata=2.0.0
  - intel-openmp=2020.2
  - jasper=1.900.1
  - jpeg=9d
  - keras=2.4.3
  - keras-base=2.4.3
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=10.0.1
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libllvm10=10.0.1
  - libopencv=4.5.0
  - libpng=1.6.37
  - libpq=12.3
  - libprotobuf=3.13.0.1
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.14
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markdown=3.3.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - multidict=4.7.6
  - mysql-common=8.0.21
  - mysql-libs=8.0.21
  - ncurses=6.2
  - nettle=3.4.1
  - nspr=4.29
  - nss=3.58
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.1.0
  - olefile=0.46
  - opencv=4.5.0
  - openh264=2.1.1
  - openssl=1.1.1h
  - opt_einsum=3.1.0
  - pango=1.42.4
  - pcre=8.44
  - pillow=8.0.1
  - pip=20.2.4
  - pixman=0.38.0
  - protobuf=3.13.0.1
  - py-opencv=4.5.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pydotplus=2.0.2
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pysocks=1.7.1
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pyyaml=5.3.1
  - qt=5.12.9
  - readline=8.0
  - requests=2.24.0
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - scipy=1.5.2
  - setuptools=50.3.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - tensorboard=2.2.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.2.0
  - tensorflow-base=2.2.0
  - tensorflow-estimator=2.2.0
  - tensorflow-gpu=2.2.0
  - termcolor=1.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - urllib3=1.25.11
  - werkzeug=1.0.1
  - wheel=0.35.1
  - wrapt=1.12.1
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.2
  - zipp=3.3.1
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1

