version: "2.4"
services:
  process_manager:
    build: .
    ports:
      - "3306:3306"
      - "5983:5983"
      - "8080:8080"
    command: ./launch.sh
    volumes:
      - "/home/migly/LAB/data:/process-manager/server/dataset:ro"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ: "Asia/Tokyo"
    runtime: nvidia
    container_name: server
    tty: true
